version: '3'

services: 

  admin-crud:
    build: 
      context: .
    container_name: admincrud
    restart: always
    working_dir: /usr/src/app
    tty: true
    ports: 
      - "3001:3001"
    expose:
      - "3001"
    command: npm run start
    networks:
      - node-network

networks:
  node-network:
    external: true
